# The root route with all parameters, which are inherited by the child
# routes if they are not overwritten.

route:
  receiver: 'default-receiver'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  group_by: [alertname]

  # All alerts that do not match the following child routes
  # will remain at the root node and be dispatched to 'default-receiver'.

  routes:
  - receiver: 'peach-page'
    group_wait: 10s
    match:
      team: "peach"
      severity: "high"
    routes:
    - receiver: 'peach'
      group_wait: 10s
      match:
        team: "peach"
        severity: "warning|medium"

  - receiver: 'apple-page'
    group_by: [alertname]
    match:
      team: "apple"

receivers:

- name: 'default-receiver'
  slack_configs:
  - channel: '#default-receiver-alerts'
    send_resolved: true
    api_url: <secret>

- name: 'peach'
  slack_configs:
  - channel: '#peach-alerts'
    send_resolved: true
    api_url: <secret>


- name: 'apple'
  slack_configs:
  - channel: '#apple-alerts'
    send_resolved: true
    api_url: <secret>
