server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: tenant1

scrape_configs:

- job_name: syslog
  static_configs:
  - targets:
      - localhost
    labels:
      job: syslog
      instance: promtail
      __path__: /var/log/*log

- job_name: docker
  static_configs:
  - targets:
      - localhost
    labels:
      job: docker
      instance: promtail
      __path__: /var/lib/docker/containers/*/*log
